//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Security.Cryptography;
using System.Xml.Serialization;

namespace AssemblyCSharp
{
	public static class XmlUtils<T> 
		where T : class 
	{
		public static T ImportFromXml(string filePath)
		{
			T t = null;
			
			try
			{
				if (File.Exists(filePath))
				{
					using (Stream stream = new FileStream(filePath, FileMode.Open))
					{
						XmlSerializer xs = new XmlSerializer(typeof(T));
						t = xs.Deserialize(stream) as T;
					}
				}
			}
			catch (Exception)
			{
				//error
				t = null;
			}
			
			
			return t;
		}
		
		public static bool ExportToXml(T t, string filePath)
		{
			bool isSuccess = false;
			try
			{
				using (Stream stream = new FileStream(filePath, FileMode.Create))
				{
					XmlSerializer xs = new XmlSerializer(typeof(T));
					xs.Serialize(stream, t);
				}
				isSuccess = true;
			}
			catch (Exception e)
			{
				//error
				isSuccess = false;
			}
			
			return isSuccess;
		}
	}
}

